const mongoose=require("mongoose");

const couponSchema=new mongoose.Schema({
    code:{
        type:String,
        required:true,
        unique:true,
    },
    discountPercentage:{
        type:Number,
        required:true,
        min:0,
        max:100,
    },
    minPurchaseAmount:{
        type:Number,
        required:true,
        min:0,
    },
    maxDiscountAmount:{
        type:Number,
        required:true,
        min:0,
    },
    validFrom:{
        type:Date,
        required:true,
    },
    validUntil:{
        type:Date,
        required:true,
    },
    isActive:{
        type:Boolean,
        default:true,
    },
    usageLimit:{
        type:Number,
        required:true,
        min:0,
    },
    usedCount:{
        type:Number,
        default:0,
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
    },
    createdAt:{
        type:Date,
        default:Date.now,
    },
    updatedAt:{
        type:Date,
        default:Date.now,
    },
});

module.exports=mongoose.model("Coupon",couponSchema);